export const data=[
  {
    "name": "base zombie",
    "id": "base",
    "hp": "7",
    "speed": "90",
    "melee": "munch",
    "cooldown": "0",
    "damage": "0.1",
    "splash": "",
    "movementFrames": "2",
    "attackFrames": "0",
    "power ": "-",
    "powerInterval": "-",
    "powerVariant": "-",
    "powerDamage": "-",
    "powerSplash": "-",
    "takesDamageLanes": "0",
    "doesDamageLanes": "0"
  },
  {
    "name": "mohawk",
    "id": "mohawk",
    "hp": "5",
    "speed": "100",
    "melee": "munch",
    "cooldown": "0",
    "damage": "0.3",
    "splash": "",
    "movementFrames": "1",
    "attackFrames": "0",
    "power ": "shoot",
    "powerInterval": "5",
    "powerVariant": "guitar",
    "powerDamage": "1",
    "powerSplash": "u1=0.5,d1=0.5",
    "takesDamageLanes": "0",
    "doesDamageLanes": "0"
  },
  {
    "name": "top hat ",
    "id": "hat",
    "hp": "14",
    "speed": "45",
    "melee": "munch",
    "cooldown": "0",
    "damage": "0.1",
    "splash": "",
    "movementFrames": "2",
    "attackFrames": "0",
    "power ": "-",
    "powerInterval": "-",
    "powerVariant": "-",
    "powerDamage": "-",
    "powerSplash": "-",
    "takesDamageLanes": "0",
    "doesDamageLanes": "0"
  },
  {
    "name": "baker",
    "id": "bake",
    "hp": "7",
    "speed": "75",
    "melee": "munch",
    "cooldown": "0",
    "damage": "0.2",
    "splash": "",
    "movementFrames": "2",
    "attackFrames": "0",
    "power ": "throw",
    "powerInterval": "8.5",
    "powerVariant": "bread",
    "powerDamage": "1",
    "powerSplash": "",
    "takesDamageLanes": "0",
    "doesDamageLanes": "0"
  },
  {
    "name": "big boy",
    "id": "tank",
    "hp": "100",
    "speed": "10",
    "melee": "munch",
    "cooldown": "0.5",
    "damage": "5",
    "splash": "l1=0.5,u1=0.5,d1=0.5",
    "movementFrames": "2",
    "attackFrames": "0",
    "power ": "shockwave",
    "powerInterval": "",
    "powerVariant": "-",
    "powerDamage": "",
    "powerSplash": "l2=0.25,l1=0.5",
    "takesDamageLanes": "0,-1",
    "doesDamageLanes": "0,-1,1",
    "eextra": "ONLY SPAWN IN LATE ROUNDS"
  }
]